"""Spec-aligned reference-runtime interfaces for vocabulary enrichment.

The existing ontology experiments remain available for comparison.  This
package is the conformance boundary: it preserves source vocabulary meaning,
binds candidates to immutable inputs, and refuses legacy flat registry rows as
production output.
"""

from spicy_regs.enrichment.reference_runtime import (
    CANONICAL_JSON_POLICY,
    CONCEPT_EVENT_PARTICIPANT_COLUMNS,
    CONCEPT_LABEL_COLUMNS,
    CONCEPT_RELATION_COLUMNS,
    DEVELOPMENT_DATASET_ID,
    REQUIRED_IMPORT_FEATURES,
    ConceptEventParticipant,
    ConceptLabel,
    ConceptRelation,
    CoverageException,
    EnrichmentConfiguration,
    EnrichmentDeploymentDecision,
    EnrichmentEvaluationResult,
    EnrichmentProfile,
    ImportFeatureCoverage,
    IndexedVocabularyExpression,
    LegacyMigrationBatch,
    OutputProfile,
    ReferenceRuntimeError,
    ReferenceRuntimeStore,
    RegistryDeploymentDecision,
    RegistryImportCoverageReport,
    RegistryReconciliationReport,
    VocabularyUniverseFreeze,
    adapt_source_terms_for_migration,
    assert_conforming_vocabulary_rows,
    bind_ranked_candidates,
    canonical_payload_digest,
    canonical_text_digest,
    indexed_expression_id,
    materialize_open_label_value_assertion,
    migrate_legacy_concepts,
    normalize_unicode_text,
    reject_legacy_conforming_payload,
    require_payload_digest,
    require_vocabulary_universe_freeze,
    seal_payload,
    validate_lifecycle_participants,
)

__all__ = [
    "CANONICAL_JSON_POLICY",
    "CONCEPT_EVENT_PARTICIPANT_COLUMNS",
    "CONCEPT_LABEL_COLUMNS",
    "CONCEPT_RELATION_COLUMNS",
    "DEVELOPMENT_DATASET_ID",
    "REQUIRED_IMPORT_FEATURES",
    "ConceptEventParticipant",
    "ConceptLabel",
    "ConceptRelation",
    "CoverageException",
    "EnrichmentConfiguration",
    "EnrichmentDeploymentDecision",
    "EnrichmentEvaluationResult",
    "EnrichmentProfile",
    "ImportFeatureCoverage",
    "IndexedVocabularyExpression",
    "LegacyMigrationBatch",
    "OutputProfile",
    "ReferenceRuntimeError",
    "ReferenceRuntimeStore",
    "RegistryDeploymentDecision",
    "RegistryImportCoverageReport",
    "RegistryReconciliationReport",
    "VocabularyUniverseFreeze",
    "adapt_source_terms_for_migration",
    "assert_conforming_vocabulary_rows",
    "bind_ranked_candidates",
    "canonical_payload_digest",
    "canonical_text_digest",
    "indexed_expression_id",
    "materialize_open_label_value_assertion",
    "migrate_legacy_concepts",
    "normalize_unicode_text",
    "reject_legacy_conforming_payload",
    "require_payload_digest",
    "require_vocabulary_universe_freeze",
    "seal_payload",
    "validate_lifecycle_participants",
]
