"""Readers for the Office of the Law Revision Counsel's two act-relative tables.

An act-relative citation — "Clean Air Act section 111" — names no code, title or
section number, so no expression can resolve it. It is a **data** problem, and
the data is two OLRC tables that this module reads.

**The Popular Name Tool** (:data:`POPULAR_NAMES_URL`) answers *which act*. It is
one machine-generated page carrying every popular name Congress has used, each
with the enacting act's Table III key, and often the U.S. Code section where the
act's short title lives ("Clean Air Act" → ``42:7401``). It also carries the
aliases, which is what makes acronyms resolvable without hand-curation: "ERISA"
is an entry in its own right, pointing at "Employee Retirement Income Security
Act".

**Table III** (:func:`table3_url`) answers *which section*. One page per act,
keyed by the same Table III key, mapping each **act section** to the U.S. Code
title and section it was classified to. "Clean Air Act" is ``1955:360``, and its
Table III row for act section 111 reads title 42, section 7411 — which is the
answer, and is not derivable by arithmetic from anything else.

Both are read as *pure parsers over bytes*: :func:`parse_popular_names` and
:func:`parse_table3` take HTML text and return records, so every shape this
module claims to read is pinned by a test against real captured bytes rather
than by a live request. The readers add fetching and an on-disk cache on top.

**Why regular expressions rather than a DOM parse.** Both pages are generated by
the same JSF application and emit one flat, attribute-carrying element per
record — ``<div class='popular-name-table-entry'>`` and ``<tr
class="table3row_*">`` — with the identifying facts in attributes
(``t3searchkey``, ``usckey``, ``content-type``) rather than in nesting. There is
no tree to walk, the Popular Name Tool is 11 MB, and the expressions below are
asserted against captured bytes. A DOM parse would buy structure this markup
does not use.
"""

from __future__ import annotations

import re
import time
from collections.abc import Iterator
from dataclasses import dataclass
from html import unescape
from pathlib import Path

import httpx
from loguru import logger

from spicy_regs.sources.base import Reader

#: The whole Popular Name Tool, one page, ~11 MB.
POPULAR_NAMES_URL = "https://uscode.house.gov/popularnames/popularnames.htm"

#: Table III, one page per enacting act, keyed by :data:`_TABLE3_KEY`.
TABLE3_URL_TEMPLATE = "https://uscode.house.gov/table3/{key}.htm"

#: A descriptive UA rather than httpx's default; uscode.house.gov serves
#: anonymously and is not UA-gated, but the client should say who it is.
_USER_AGENT = "spicy-regs-etl/1.0 (+https://github.com/civictechdc/spicy-regs)"

_TIMEOUT = httpx.Timeout(120.0, connect=30.0)
_MAX_RETRIES = 4

#: A Table III key is either a Public Law ("90-148") or a pre-1957 session-law
#: chapter ("1955:360"). The URL spells both separators with an underscore.
#:
#: The Congress number is bounded because without it the two shapes overlap:
#: "1955-360" would read as Public Law 1955-360, and there is no 1955th
#: Congress. The bound is generous (199) rather than the current 119, so the
#: expression outlives the decade without licensing a year.
_TABLE3_KEY = re.compile(r"^(?:[1-9]\d{0,2}-[1-9]\d*|(?:1[789]|20)\d{2}:[1-9]\d*)$")
_TABLE3_KEY_SEPARATOR = re.compile(r"[:-]")

#: One popular-name entry. The name is in its own paragraph; each following
#: information paragraph carries a ``content-type`` and, depending on the type,
#: a Table III key and a U.S. Code anchor.
_POPULAR_NAME_ENTRY = re.compile(
    r"<div id='(?P<anchor>[^']*)' class='popular-name-table-entry'"
    r"(?:[^>]*?release-point='(?P<release_point>[^']*)')?[^>]*>"
    r"(?P<body>.*?)</div>",
    re.DOTALL,
)
_POPULAR_NAME = re.compile(r"<p class='popular-name'>(?P<name>.*?)</p>", re.DOTALL)
_POPULAR_NAME_INFORMATION = re.compile(
    r"<p class='popular-name-information'(?P<attributes>[^>]*)>(?P<text>.*?)</p>",
    re.DOTALL,
)
_ATTRIBUTE = re.compile(r"(?P<name>[a-z0-9_-]+)='(?P<value>[^']*)'")

#: "See Employee Retirement Income Security Act" — the alias target.
_SEE_TARGET = re.compile(r"^\s*(?:see|renamed(?:\s+as)?)\s+(?P<target>.+?)\s*$", re.IGNORECASE)

#: A ``usckey`` is ``title:section``; the section may carry a subsection the
#: U.S.C. identifier grammar excludes ("15:12(b)").
_USC_KEY = re.compile(r"^(?P<title>[1-9]\d*):(?P<section>[^\s:]+)$")

_TABLE3_ROW = re.compile(r'<tr class="table3row_(?:odd|even)">(?P<body>.*?)</tr>', re.DOTALL)
_TABLE3_CELL = re.compile(r'<td class="(?P<column>[a-z]+)"[^>]*>(?P<value>.*?)</td>', re.DOTALL)
_TAG = re.compile(r"<[^>]*>")


def _text(fragment: str) -> str:
    """The visible text of an HTML fragment, whitespace collapsed."""
    return re.sub(r"\s+", " ", unescape(_TAG.sub("", fragment))).strip()


def table3_url(key: str) -> str:
    """The Table III page for an enacting act.

    ``"1955:360"`` and ``"90-148"`` are the two spellings the Popular Name Tool
    emits; both become an underscore in the path. A key of any other shape is
    refused rather than turned into a URL that would 404 — a fetch loop over
    thousands of acts should fail on the key, not on the response.
    """
    if not _TABLE3_KEY.fullmatch(key or ""):
        raise ValueError(f"invalid Table III key: {key!r}")
    return TABLE3_URL_TEMPLATE.format(key=_TABLE3_KEY_SEPARATOR.sub("_", key))


@dataclass(frozen=True)
class PopularNameRecord:
    """One popular name and one thing the tool says about it.

    An entry may carry several information paragraphs — the enacting citation,
    a short-title reference, an alias — so one name can yield several records.
    ``content_type`` is the tool's own vocabulary (``cite``, ``see``,
    ``also-known-as``, ``renamed``, ``short-title-ref``), kept verbatim rather
    than collapsed, because the distinction between "this act is" and "this name
    means" is the difference between an identity and a redirect.
    """

    name: str
    content_type: str
    table3_key: str | None = None
    usc_title: str | None = None
    usc_section: str | None = None
    see_also: str | None = None
    release_point: str | None = None
    stated: str | None = None


@dataclass(frozen=True)
class Table3Record:
    """One act section and the U.S. Code place it was classified to.

    ``usc_section`` is ``None`` where the act section was repealed, omitted, or
    otherwise classified nowhere — the row exists and says so, and dropping it
    would turn "we know this went nowhere" into "we do not know".
    """

    act_section: str
    usc_title: str | None = None
    usc_section: str | None = None
    status: str | None = None
    statutes_at_large_page: str | None = None


def parse_popular_names(document: str) -> list[PopularNameRecord]:
    """Parse the Popular Name Tool page into one record per stated fact."""
    records: list[PopularNameRecord] = []
    for entry in _POPULAR_NAME_ENTRY.finditer(document):
        body = entry.group("body")
        heading = _POPULAR_NAME.search(body)
        if heading is None:
            continue
        name = _text(heading.group("name"))
        if not name:
            continue
        release_point = entry.group("release_point")
        for information in _POPULAR_NAME_INFORMATION.finditer(body):
            attributes = dict(_ATTRIBUTE.findall(information.group("attributes")))
            content_type = attributes.get("content-type")
            if not content_type:
                continue
            stated = _text(information.group("text"))
            usc_title, usc_section = _split_usc_key(attributes.get("usckey"))
            alias = _SEE_TARGET.match(stated) if content_type in {"see", "renamed"} else None
            records.append(
                PopularNameRecord(
                    name=name,
                    content_type=content_type,
                    table3_key=attributes.get("t3searchkey") or None,
                    usc_title=usc_title,
                    usc_section=usc_section,
                    see_also=alias.group("target") if alias else None,
                    release_point=release_point,
                    stated=stated or None,
                )
            )
    return records


def _split_usc_key(key: str | None) -> tuple[str | None, str | None]:
    match = _USC_KEY.fullmatch(key) if key else None
    return (match.group("title"), match.group("section")) if match else (None, None)


def parse_table3(document: str) -> list[Table3Record]:
    """Parse one Table III page into one record per act section."""
    records: list[Table3Record] = []
    for row in _TABLE3_ROW.finditer(document):
        cells = {column: _text(value) for column, value in _TABLE3_CELL.findall(row.group("body"))}
        act_section = cells.get("actsection", "")
        if not act_section:
            continue
        records.append(
            Table3Record(
                act_section=act_section,
                usc_title=cells.get("unitedstatescodetitle") or None,
                usc_section=cells.get("unitedstatescodesection") or None,
                status=cells.get("unitedstatescodestatus") or None,
                statutes_at_large_page=cells.get("statutesatlargepage") or None,
            )
        )
    return records


def fetch(url: str, *, cache_dir: Path | None = None) -> str:
    """Fetch a page, optionally through an on-disk cache.

    These pages are release-pointed rather than live — the Popular Name Tool is
    11 MB and Table III is one request per act — so a cached build is the normal
    build and a cold one is the exception.
    """
    cached = (cache_dir / _cache_name(url)) if cache_dir else None
    if cached is not None and cached.exists():
        return cached.read_text(encoding="utf-8")
    document = _get(url)
    if cached is not None:
        cached.parent.mkdir(parents=True, exist_ok=True)
        cached.write_text(document, encoding="utf-8")
    return document


def _cache_name(url: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "_", url.split("://", 1)[-1])


def _get(url: str) -> str:
    headers = {"User-Agent": _USER_AGENT}
    last: Exception | None = None
    for attempt in range(_MAX_RETRIES):
        try:
            response = httpx.get(url, headers=headers, timeout=_TIMEOUT, follow_redirects=True)
            response.raise_for_status()
            return response.text
        except httpx.HTTPError as error:  # pragma: no cover - network path
            last = error
            delay = 2**attempt
            logger.warning("OLRC fetch failed ({}), retrying in {}s: {}", url, delay, error)
            time.sleep(delay)
    raise RuntimeError(f"OLRC fetch failed after {_MAX_RETRIES} attempts: {url}") from last


class PopularNamesReader(Reader):
    """Yields every stated fact in the Popular Name Tool, as raw dicts."""

    def __init__(self, *, cache_dir: Path | None = None, url: str = POPULAR_NAMES_URL) -> None:
        self.cache_dir = cache_dir
        self.url = url

    def iter_records(self) -> Iterator[dict]:
        document = fetch(self.url, cache_dir=self.cache_dir)
        records = parse_popular_names(document)
        logger.info("Popular Name Tool: {:,} stated facts", len(records))
        self.last_keys = [self.url]
        for record in records:
            yield record.__dict__.copy()


class Table3Reader(Reader):
    """Yields Table III classifications for the enacting acts it is given.

    The act keys are supplied rather than discovered: Table III is one request
    per act and the Popular Name Tool lists thousands, so the caller decides
    which acts are worth a request. A key whose page cannot be fetched goes on
    ``failed_keys`` and is not manifested, so the next run retries it.
    """

    def __init__(self, keys: list[str], *, cache_dir: Path | None = None) -> None:
        self.keys = keys
        self.cache_dir = cache_dir

    def iter_records(self) -> Iterator[dict]:
        self.last_keys, self.failed_keys = [], []
        for key in self.keys:
            try:
                document = fetch(table3_url(key), cache_dir=self.cache_dir)
            except (RuntimeError, ValueError) as error:
                logger.warning("Table III unavailable for {}: {}", key, error)
                self.failed_keys.append(key)
                continue
            self.last_keys.append(key)
            for record in parse_table3(document):
                yield {"table3_key": key, **record.__dict__}
