// Worker entrypoint fronting the MCP container (Cloudflare Containers).
//
// The container runs the canonical Python MCP server (see ../Dockerfile) on
// port 8080; this Worker forwards /mcp requests to it. getContainer with no name
// routes every request to one instance ("cf-singleton-container"), whatever
// max_instances allows. The server is stateless (stateless_http), so more
// instances would answer correctly, but each would build its own connection
// against the public bucket; the server runs tool calls concurrently instead
// (SPICY_REGS_TOOL_CONCURRENCY).
//
// `Env` is generated by `wrangler types` (worker-configuration.d.ts) from the
// bindings in wrangler.jsonc — it types MCP_CONTAINER as the DO namespace.
import { Container, getContainer } from "@cloudflare/containers";

export class McpContainer extends Container<Env> {
  defaultPort = 8080;
  // Idle timeout before the instance is reclaimed (scale-to-zero economics).
  sleepAfter = "20m";

  override async fetch(request: Request): Promise<Response> {
    const response = await super.fetch(request);
    const container = this.ctx.container;
    if (response.status === 500 && container?.running) {
      // After a rollout the native connection can claim to be running while
      // its port refuses traffic. Confirm that contradiction independently of
      // the application's response body; a normal application 500 passes through.
      try {
        const probe = await container.getTcpPort(this.defaultPort).fetch(
          "http://containerhealthcheck/",
          { method: "HEAD", signal: AbortSignal.timeout(2000) },
        );
        await probe.body?.cancel();
      } catch (error) {
        if (
          error instanceof Error &&
          error.message === "The container is not running, consider calling start()"
        ) {
          // The SDK uses the same reset for a stale native connection during
          // startup. Abort reconnects on the next request; never replay this one.
          this.ctx.abort("Resetting stale MCP container connection after port refusal");
        }
      }
    }
    return response;
  }

  // DuckDB tuning + R2 read config. Memory is capped under
  // standard-4's 12 GiB so a heavy query spills to the real 20 GB disk (/tmp)
  // rather than being OOM-killed.
  //
  // Wrangler vars and the optional catalog secret must reach Python explicitly.
  // Without complete catalog settings, Python uses this account's public mirror.
  envVars = {
    SPICY_REGS_MEMORY_LIMIT: "9GB",
    SPICY_REGS_TEMP_DIR: "/tmp",
    SPICY_REGS_HOME_DIR: "/tmp",
    SPICY_REGS_STATEMENT_TIMEOUT: "600s",
    SPICY_REGS_R2_URL: this.env.SPICY_REGS_R2_URL,
    SPICY_REGS_FEC_RELEASE_SHA256: this.env.SPICY_REGS_FEC_RELEASE_SHA256,
    SPICY_REGS_CONSUMER_IMAGE_DIGEST: this.env.SPICY_REGS_CONSUMER_IMAGE_DIGEST,
    R2_CATALOG_URI: this.env.R2_CATALOG_URI,
    R2_CATALOG_WAREHOUSE: this.env.R2_CATALOG_WAREHOUSE,
    R2_CATALOG_NAMESPACE: this.env.R2_CATALOG_NAMESPACE,
    // The optional secret is installed separately, so it is not a required
    // binding in generated Env types. Check its runtime type before forwarding.
    R2_CATALOG_TOKEN:
      "R2_CATALOG_TOKEN" in this.env && typeof this.env.R2_CATALOG_TOKEN === "string"
        ? this.env.R2_CATALOG_TOKEN
        : "",
  };
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    if (!env.SPICY_REGS_R2_URL) {
      return new Response("Data is not available yet.", { status: 503 });
    }
    const { pathname } = new URL(request.url);
    // /mcp is the protocol endpoint; / and /icon.png are the human-facing setup
    // page, which the Python server serves (see mcp_server._register_landing_page).
    if (
      pathname === "/mcp" ||
      pathname.startsWith("/mcp/") ||
      pathname === "/" ||
      pathname === "/icon.png"
    ) {
      return getContainer(env.MCP_CONTAINER).fetch(request);
    }
    return new Response("Not found", { status: 404 });
  },
} satisfies ExportedHandler<Env>;
