"""Reviewed domain columns for the regulations family.

Source columns declare processor inputs independently from public subject fields.
Source spelling and conversion evidence are retained by regulations_shape.
"""

SOURCE_COLUMNS = {
    "agency_lifecycle_stats": [
        ("agency_code", "VARCHAR"),
        ("stratum", "VARCHAR"),
        ("rules", "INTEGER"),
        ("finals", "INTEGER"),
        ("withdrawals", "INTEGER"),
        ("censored", "INTEGER"),
        ("suppressed", "BOOLEAN"),
        ("q1_days", "INTEGER"),
        ("q1_lower_days", "INTEGER"),
        ("q1_upper_days", "INTEGER"),
        ("median_days", "INTEGER"),
        ("median_lower_days", "INTEGER"),
        ("median_upper_days", "INTEGER"),
        ("q3_days", "INTEGER"),
        ("q3_lower_days", "INTEGER"),
        ("q3_upper_days", "INTEGER"),
        ("censor_date", "DATE"),
        ("method", "VARCHAR"),
        ("actor_id", "VARCHAR"),
        ("run_id", "VARCHAR"),
        ("asserted_at", "VARCHAR"),
        ("supersedes_id", "VARCHAR"),
    ],
    "agency_monthly_volume": [
        ("agency_code", "VARCHAR"),
        ("year", "BIGINT"),
        ("month", "BIGINT"),
        ("document_type", "VARCHAR"),
        ("document_count", "BIGINT"),
    ],
    "agency_stats": [
        ("agency_code", "VARCHAR"),
        ("docket_count", "BIGINT"),
        ("document_count", "BIGINT"),
        ("comment_count", "BIGINT"),
    ],
    "agenda_item_proceedings": [
        ("relationship_id", "VARCHAR"),
        ("agenda_item_id", "VARCHAR"),
        ("rin", "VARCHAR"),
        ("proceeding_id", "VARCHAR"),
        ("relationship_role", "VARCHAR"),
        ("source", "VARCHAR"),
        ("evidence_id", "VARCHAR"),
        ("evidence_uri", "VARCHAR"),
        ("evidence_date", "VARCHAR"),
        ("method", "VARCHAR"),
        ("actor_id", "VARCHAR"),
        ("run_id", "VARCHAR"),
        ("asserted_at", "VARCHAR"),
        ("supersedes_id", "VARCHAR"),
    ],
    "cfr_sections": [
        ("granule_id", "VARCHAR"),
        ("part_granule", "VARCHAR"),
        ("package_id", "VARCHAR"),
        ("cfr_ref", "VARCHAR"),
        ("title", "VARCHAR"),
        ("part", "VARCHAR"),
        ("section", "VARCHAR"),
        ("heading", "VARCHAR"),
        ("structure_level", "VARCHAR"),
        ("edition_year", "VARCHAR"),
        ("last_modified", "VARCHAR"),
        ("url", "VARCHAR"),
    ],
    "comment_attributes": [
        ("comment_id", "VARCHAR"),
        ("address1", "VARCHAR"),
        ("address2", "VARCHAR"),
        ("city", "VARCHAR"),
        ("country", "VARCHAR"),
        ("display_properties_json", "VARCHAR"),
        ("doc_abstract", "VARCHAR"),
        ("field1", "VARCHAR"),
        ("field2", "VARCHAR"),
        ("file_formats_json", "VARCHAR"),
        ("gov_agency", "VARCHAR"),
        ("gov_agency_type", "VARCHAR"),
        ("legacy_id", "VARCHAR"),
        ("object_id", "VARCHAR"),
        ("page_count", "INTEGER"),
        ("postmark_date", "TIMESTAMP WITH TIME ZONE"),
        ("reason_withdrawn", "VARCHAR"),
        ("restrict_reason", "VARCHAR"),
        ("restrict_reason_type", "VARCHAR"),
        ("state_province_region", "VARCHAR"),
        ("submitter_rep", "VARCHAR"),
        ("submitter_rep_address", "VARCHAR"),
        ("submitter_rep_city_state", "VARCHAR"),
        ("tracking_nbr", "VARCHAR"),
        ("withdrawn", "BOOLEAN"),
        ("zip", "VARCHAR"),
    ],
    "comment_periods": [
        ("comment_period_id", "VARCHAR"),
        ("proceeding_ids_json", "VARCHAR"),
        ("rins_json", "VARCHAR"),
        ("docket_ids_json", "VARCHAR"),
        ("open_date", "VARCHAR"),
        ("close_date", "VARCHAR"),
        ("source", "VARCHAR"),
        ("opened_by_artifact_ids_json", "VARCHAR"),
        ("evidence_ids_json", "VARCHAR"),
        ("method", "VARCHAR"),
        ("actor_id", "VARCHAR"),
        ("run_id", "VARCHAR"),
        ("asserted_at", "VARCHAR"),
        ("supersedes_id", "VARCHAR"),
        ("unresolved_fr_references_json", "VARCHAR"),
        ("anchor_kind", "VARCHAR"),
        ("register_close_date", "VARCHAR"),
        ("regulations_gov_close_date", "VARCHAR"),
    ],
    "comments": [
        ("comment_id", "VARCHAR"),
        ("docket_id", "VARCHAR"),
        ("comment_on_document_id", "VARCHAR"),
        ("comment_on_object_id", "VARCHAR"),
        ("original_document_id", "VARCHAR"),
        ("comment_reference_values_json", "VARCHAR"),
        ("agency_code", "VARCHAR"),
        ("first_name", "VARCHAR"),
        ("last_name", "VARCHAR"),
        ("organization", "VARCHAR"),
        ("category", "VARCHAR"),
        ("title", "VARCHAR"),
        ("comment", "VARCHAR"),
        ("document_type", "VARCHAR"),
        ("posted_date", "VARCHAR"),
        ("modify_date", "VARCHAR"),
        ("receive_date", "VARCHAR"),
        ("attachments_json", "VARCHAR"),
        ("text_content", "VARCHAR"),
        ("text_extraction_status", "VARCHAR"),
        ("pdf_extraction_results_json", "VARCHAR"),
        ("subtype", "VARCHAR"),
        ("duplicate_comments", "INTEGER"),
    ],
    "comments_index": [
        ("agency_code", "VARCHAR"),
        ("docket_id", "VARCHAR"),
        ("year", "BIGINT"),
        ("month", "BIGINT"),
        ("row_count", "BIGINT"),
    ],
    "discovery_signals": [
        ("agency_code", "VARCHAR"),
        ("recent_30d", "BIGINT"),
        ("baseline", "DOUBLE"),
        ("ratio", "DOUBLE"),
    ],
    "docket_attributes": [
        ("docket_id", "VARCHAR"),
        ("category", "VARCHAR"),
        ("display_properties_json", "VARCHAR"),
        ("effective_date", "TIMESTAMP WITH TIME ZONE"),
        ("field1", "VARCHAR"),
        ("field2", "VARCHAR"),
        ("generic", "VARCHAR"),
        ("keywords", "VARCHAR[]"),
        ("legacy_id", "VARCHAR"),
        ("object_id", "VARCHAR"),
        ("organization", "VARCHAR"),
        ("petition_nbr", "VARCHAR"),
        ("program", "VARCHAR"),
        ("short_title", "VARCHAR"),
        ("sub_type", "VARCHAR"),
        ("sub_type2", "VARCHAR"),
    ],
    "dockets": [
        ("docket_id", "VARCHAR"),
        ("agency_code", "VARCHAR"),
        ("title", "VARCHAR"),
        ("docket_type", "VARCHAR"),
        ("modify_date", "VARCHAR"),
        ("abstract", "VARCHAR"),
        ("rin", "VARCHAR"),
    ],
    "document_attributes": [
        ("document_id", "VARCHAR"),
        ("address1", "VARCHAR"),
        ("address2", "VARCHAR"),
        ("allow_late_comments", "BOOLEAN"),
        ("author_date", "TIMESTAMP WITH TIME ZONE"),
        ("authors", "VARCHAR[]"),
        ("category", "VARCHAR"),
        ("cfr_part", "VARCHAR"),
        ("city", "VARCHAR"),
        ("comment", "VARCHAR"),
        ("country", "VARCHAR"),
        ("display_properties_json", "VARCHAR"),
        ("doc_abstract", "VARCHAR"),
        ("effective_date", "TIMESTAMP WITH TIME ZONE"),
        ("exhibit_location", "VARCHAR"),
        ("exhibit_type", "VARCHAR"),
        ("fax", "VARCHAR"),
        ("field1", "VARCHAR"),
        ("field2", "VARCHAR"),
        ("first_name", "VARCHAR"),
        ("fr_vol_num", "VARCHAR"),
        ("gov_agency", "VARCHAR"),
        ("gov_agency_type", "VARCHAR"),
        ("implementation_date", "TIMESTAMP WITH TIME ZONE"),
        ("last_name", "VARCHAR"),
        ("legacy_id", "VARCHAR"),
        ("media", "VARCHAR"),
        ("object_id", "VARCHAR"),
        ("omb_approval", "VARCHAR"),
        ("open_for_comment", "BOOLEAN"),
        ("organization", "VARCHAR"),
        ("original_document_id", "VARCHAR"),
        ("page_count", "INTEGER"),
        ("postmark_date", "TIMESTAMP WITH TIME ZONE"),
        ("receive_date", "TIMESTAMP WITH TIME ZONE"),
        ("reg_writer_instruction", "VARCHAR"),
        ("restrict_reason", "VARCHAR"),
        ("restrict_reason_type", "VARCHAR"),
        ("source_citation", "VARCHAR"),
        ("start_end_page", "VARCHAR"),
        ("state_province_region", "VARCHAR"),
        ("subject", "VARCHAR"),
        ("submitter_rep", "VARCHAR"),
        ("subtype", "VARCHAR"),
        ("topics", "VARCHAR[]"),
        ("tracking_nbr", "VARCHAR"),
        ("within_comment_period", "BOOLEAN"),
        ("zip", "VARCHAR"),
    ],
    "documents": [
        ("document_id", "VARCHAR"),
        ("docket_id", "VARCHAR"),
        ("agency_code", "VARCHAR"),
        ("title", "VARCHAR"),
        ("document_type", "VARCHAR"),
        ("posted_date", "VARCHAR"),
        ("modify_date", "VARCHAR"),
        ("comment_start_date", "VARCHAR"),
        ("comment_end_date", "VARCHAR"),
        ("file_url", "VARCHAR"),
        ("attachments_json", "VARCHAR"),
        ("attachment_records_json", "VARCHAR"),
        ("fr_doc_num", "VARCHAR"),
        ("withdrawn", "VARCHAR"),
        ("reason_withdrawn", "VARCHAR"),
        ("additional_rins", "VARCHAR"),
        ("text_content", "VARCHAR"),
        ("text_extraction_status", "VARCHAR"),
        ("pdf_extraction_results_json", "VARCHAR"),
        ("publisher_status", "VARCHAR"),
        ("removed_observed_at", "VARCHAR"),
    ],
    "federal_register": [
        ("document_number", "VARCHAR"),
        ("title", "VARCHAR"),
        ("abstract", "VARCHAR"),
        ("document_type", "VARCHAR"),
        ("publication_date", "VARCHAR"),
        ("effective_on", "VARCHAR"),
        ("comments_close_on", "VARCHAR"),
        ("signing_date", "VARCHAR"),
        ("agencies_json", "VARCHAR"),
        ("agency_slugs", "VARCHAR"),
        ("docket_ids_json", "VARCHAR"),
        ("regulation_id_numbers_json", "VARCHAR"),
        ("cfr_references_json", "VARCHAR"),
        ("topics_json", "VARCHAR"),
        ("html_url", "VARCHAR"),
        ("pdf_url", "VARCHAR"),
        ("body_html_url", "VARCHAR"),
        ("volume", "VARCHAR"),
        ("start_page", "VARCHAR"),
        ("end_page", "VARCHAR"),
        ("subtype", "VARCHAR"),
        ("executive_order_number", "VARCHAR"),
        ("modify_date", "VARCHAR"),
        ("rin", "VARCHAR"),
        ("regulations_dot_gov_info_json", "VARCHAR"),
        ("regulations_dot_gov_docket_id", "VARCHAR"),
        ("regulations_dot_gov_document_id", "VARCHAR"),
        ("regulations_dot_gov_comments_count", "VARCHAR"),
        ("regulations_dot_gov_checked_at", "VARCHAR"),
        ("action", "VARCHAR"),
        ("correction_of", "VARCHAR"),
        ("corrections_json", "VARCHAR"),
        ("significant", "VARCHAR"),
    ],
    "feed_summary": [
        ("docket_id", "VARCHAR"),
        ("agency_code", "VARCHAR"),
        ("title", "VARCHAR"),
        ("docket_type", "VARCHAR"),
        ("modify_date", "VARCHAR"),
        ("abstract", "VARCHAR"),
        ("comment_count", "BIGINT"),
        ("comment_end_date", "VARCHAR"),
        ("date_created", "VARCHAR"),
    ],
    "fr_docket_links": [
        ("docket_id", "VARCHAR"),
        ("docket_source_ordinal", "BIGINT"),
        ("normalized_docket_candidates_json", "VARCHAR"),
        ("docket_normalization_rule", "VARCHAR"),
        ("document_number", "VARCHAR"),
        ("title", "VARCHAR"),
        ("abstract", "VARCHAR"),
        ("document_type", "VARCHAR"),
        ("subtype", "VARCHAR"),
        ("publication_date", "VARCHAR"),
        ("effective_on", "VARCHAR"),
        ("comments_close_on", "VARCHAR"),
        ("signing_date", "VARCHAR"),
        ("agency_slugs", "VARCHAR"),
        ("docket_ids_json", "VARCHAR"),
        ("regulation_id_numbers_json", "VARCHAR"),
        ("html_url", "VARCHAR"),
        ("pdf_url", "VARCHAR"),
        ("executive_order_number", "VARCHAR"),
        ("link_source", "VARCHAR"),
    ],
    "lifecycle_events": [
        ("proceeding_id", "VARCHAR"),
        ("document_id", "VARCHAR"),
        ("stage", "VARCHAR"),
        ("event_date", "DATE"),
        ("source", "VARCHAR"),
        ("dated_by", "VARCHAR"),
        ("evidence_id", "VARCHAR"),
        ("joined_by", "VARCHAR"),
        ("document_form", "VARCHAR"),
        ("anchor_role", "VARCHAR"),
        ("method", "VARCHAR"),
        ("actor_id", "VARCHAR"),
        ("run_id", "VARCHAR"),
        ("asserted_at", "VARCHAR"),
        ("supersedes_id", "VARCHAR"),
    ],
    "proceedings": [
        ("proceeding_id", "VARCHAR"),
        ("rin", "VARCHAR"),
        ("docket_ids_json", "VARCHAR"),
        ("title", "VARCHAR"),
        ("agency_code", "VARCHAR"),
        ("current_stage", "VARCHAR"),
        ("stage_events_json", "VARCHAR"),
        ("fr_document_numbers_json", "VARCHAR"),
        ("cfr_refs_json", "VARCHAR"),
        ("cfr_target_iris_json", "VARCHAR"),
        ("authority_refs_json", "VARCHAR"),
        ("method", "VARCHAR"),
        ("actor_id", "VARCHAR"),
        ("run_id", "VARCHAR"),
        ("asserted_at", "VARCHAR"),
        ("supersedes_id", "VARCHAR"),
        ("fr_document_ids_json", "VARCHAR"),
        ("fr_document_joins_json", "VARCHAR"),
        ("unresolved_fr_references_json", "VARCHAR"),
        ("rins_json", "VARCHAR"),
    ],
    "regulatory_agenda_items": [
        ("agenda_item_id", "VARCHAR"),
        ("rin", "VARCHAR"),
        ("scope_status", "VARCHAR"),
        ("scope_basis", "VARCHAR"),
        ("linked_proceeding_count", "VARCHAR"),
        ("observation_count", "VARCHAR"),
        ("latest_agenda_edition", "VARCHAR"),
        ("first_seen", "VARCHAR"),
        ("last_seen", "VARCHAR"),
        ("method", "VARCHAR"),
        ("actor_id", "VARCHAR"),
        ("run_id", "VARCHAR"),
        ("asserted_at", "VARCHAR"),
        ("supersedes_id", "VARCHAR"),
        ("unresolved_fr_references_json", "VARCHAR"),
    ],
    "rule_targets": [
        ("docket_id", "VARCHAR"),
        ("cfr_ref", "VARCHAR"),
        ("cfr_title", "VARCHAR"),
        ("cfr_part", "VARCHAR"),
        ("cfr_section", "VARCHAR"),
        ("rin", "VARCHAR"),
        ("source", "VARCHAR"),
        ("evidence_id", "VARCHAR"),
        ("first_seen", "VARCHAR"),
        ("last_seen", "VARCHAR"),
        ("method", "VARCHAR"),
        ("actor_id", "VARCHAR"),
        ("run_id", "VARCHAR"),
        ("asserted_at", "VARCHAR"),
        ("supersedes_id", "VARCHAR"),
        ("fr_references_json", "VARCHAR"),
    ],
    "rulemaking_lifecycles": [
        ("proceeding_id", "VARCHAR"),
        ("agency_code", "VARCHAR"),
        ("kind", "VARCHAR"),
        ("proposal_date", "DATE"),
        ("proposal_document_id", "VARCHAR"),
        ("proposal_form", "VARCHAR"),
        ("final_date", "DATE"),
        ("final_document_id", "VARCHAR"),
        ("final_form", "VARCHAR"),
        ("finals_before_proposal", "INTEGER"),
        ("withdrawal_date", "DATE"),
        ("withdrawal_document_id", "VARCHAR"),
        ("withdrawal_source", "VARCHAR"),
        ("outcome", "VARCHAR"),
        ("duration_days", "INTEGER"),
        ("censor_date", "DATE"),
        ("open_signal", "VARCHAR"),
        ("routine_family", "VARCHAR"),
        ("agenda_priority", "VARCHAR"),
        ("agenda_major", "VARCHAR"),
        ("specific_rins_json", "VARCHAR"),
        ("anchored_by_specific_rin", "BOOLEAN"),
        ("pre_2008_coverage", "BOOLEAN"),
        ("method", "VARCHAR"),
        ("actor_id", "VARCHAR"),
        ("run_id", "VARCHAR"),
        ("asserted_at", "VARCHAR"),
        ("supersedes_id", "VARCHAR"),
    ],
    "unified_agenda": [
        ("rin", "VARCHAR"),
        ("agency_code", "VARCHAR"),
        ("agency_name", "VARCHAR"),
        ("title", "VARCHAR"),
        ("abstract", "VARCHAR"),
        ("rin_status", "VARCHAR"),
        ("rule_stage", "VARCHAR"),
        ("priority_category", "VARCHAR"),
        ("agenda_edition", "VARCHAR"),
        ("major", "VARCHAR"),
        ("publication_id", "VARCHAR"),
        ("timetable_json", "VARCHAR"),
        ("cfr_references_json", "VARCHAR"),
        ("legal_authority_json", "VARCHAR"),
        ("first_action_date", "VARCHAR"),
        ("next_action_date", "VARCHAR"),
        ("url", "VARCHAR"),
    ],
}

RECEIPT_COLUMNS = {
    "agency_lifecycle_stats": ("method", "actor_id", "run_id", "asserted_at", "supersedes_id"),
    "agency_monthly_volume": (),
    "agency_stats": (),
    "agenda_item_proceedings": (
        "source",
        "evidence_id",
        "evidence_uri",
        "evidence_date",
        "method",
        "actor_id",
        "run_id",
        "asserted_at",
        "supersedes_id",
    ),
    "cfr_sections": ("url",),
    "comment_attributes": (),
    # anchor_kind and evidence_ids are subject columns: what anchors a period, and which documents state its dates,
    # are facts about the period a reader filters on and follows, not how the row was processed (owner decisions,
    # 2026-10-05).
    "comment_periods": (
        "source",
        "method",
        "actor_id",
        "run_id",
        "asserted_at",
        "supersedes_id",
        "unresolved_fr_references_json",
    ),
    "comments": ("comment_reference_values_json", "text_extraction_status", "pdf_extraction_results_json"),
    "comments_index": (),
    "discovery_signals": (),
    "docket_attributes": (),
    "dockets": (),
    "document_attributes": (),
    "documents": ("file_url", "text_extraction_status", "pdf_extraction_results_json"),
    "federal_register": ("html_url", "pdf_url", "body_html_url", "regulations_dot_gov_info_json"),
    "feed_summary": (),
    "fr_docket_links": ("docket_normalization_rule", "html_url", "pdf_url", "normalized_docket_candidates_json"),
    "lifecycle_events": (
        "source",
        "dated_by",
        "evidence_id",
        "joined_by",
        "method",
        "actor_id",
        "run_id",
        "asserted_at",
        "supersedes_id",
    ),
    "proceedings": (
        "method",
        "actor_id",
        "run_id",
        "asserted_at",
        "supersedes_id",
        "fr_document_joins_json",
        "unresolved_fr_references_json",
    ),
    "regulatory_agenda_items": (
        "scope_basis",
        "method",
        "actor_id",
        "run_id",
        "asserted_at",
        "supersedes_id",
        "unresolved_fr_references_json",
    ),
    "rule_targets": (
        "source",
        "evidence_id",
        "method",
        "actor_id",
        "run_id",
        "asserted_at",
        "supersedes_id",
        "fr_references_json",
    ),
    "rulemaking_lifecycles": (
        "withdrawal_source",
        "anchored_by_specific_rin",
        "method",
        "actor_id",
        "run_id",
        "asserted_at",
        "supersedes_id",
    ),
    "unified_agenda": ("url",),
}
